"""Permisos base asignados a roles del sistema."""


DEFAULT_ROLE_PERMISSION_CODES = {
    'Supervisor': [
        'crear_venta', 'ver_ventas', 'ver_detalle_venta', 'aplicar_descuento', 'venta_credito',
        'vender_sin_stock',
        'ver_inventario', 'crear_producto', 'editar_producto', 'ver_costo_compra',
        'crear_compra', 'ver_compras', 'pagar_compra',
        'abrir_caja', 'cerrar_caja', 'ver_caja', 'movimiento_caja', 'ver_otras_cajas',
        'enviar_caja_venta', 'enviar_caja_reparacion', 'ver_cola_cobro', 'tomar_cola_cobro',
        'crear_cliente', 'editar_cliente', 'ver_clientes',
        'crear_proveedor', 'editar_proveedor', 'ver_proveedores',
        'ver_reportes', 'ver_reporte_ventas', 'ver_reporte_inventario', 'ver_reporte_financiero', 'exportar_reportes',
        'ver_configuracion',
        'ver_reparaciones', 'crear_reparacion', 'editar_reparacion', 'cambiar_estado_reparacion', 'cobrar_reparacion',
        'vincular_venta_reparacion',
        'ver_recepcion_usados', 'crear_recepcion_usados',
        'ver_presupuestos_empresariales', 'crear_presupuestos_empresariales',
        'whatsapp_conversaciones', 'crm_whatsapp', 'crm_operar_como_asesor',
        'agenda_acceso', 'agenda_ver_todas', 'agenda_crear', 'agenda_editar', 'agenda_completar', 'agenda_cancelar',
        'ver_control_empleados', 'gestionar_control_empleados',
        'ver_cobranzas', 'registrar_cobro_credito', 'anular_cobro_credito',
        'gestionar_promesa_pago', 'enviar_recordatorio_cobranza', 'ver_reportes_cobranzas',
        'ver_gastos_corrientes', 'crear_gastos_corrientes', 'editar_gastos_corrientes',
        'registrar_pago_gasto_corriente', 'anular_pago_gasto_corriente',
        'ver_reportes_gastos_corrientes', 'ver_flujo_caja', 'gestionar_flujo_caja',
        'gastronomia_acceso', 'gastronomia_menu', 'gastronomia_pos',
        'gastronomia_cocina', 'gastronomia_caja', 'gastronomia_salon',
        'gastronomia_delivery', 'gastronomia_reportes',
    ],
    'Cajero': [
        'crear_venta', 'ver_ventas', 'ver_detalle_venta', 'aplicar_descuento',
        'vender_sin_stock', 'ver_inventario',
        'abrir_caja', 'cerrar_caja', 'ver_caja', 'movimiento_caja',
        'ver_cola_cobro', 'tomar_cola_cobro',
        'crear_cliente', 'ver_clientes', 'ver_proveedores',
        'ver_reparaciones', 'crear_reparacion', 'editar_reparacion', 'cambiar_estado_reparacion', 'cobrar_reparacion',
        'vincular_venta_reparacion',
        'ver_recepcion_usados', 'crear_recepcion_usados',
        'ver_presupuestos_empresariales', 'crear_presupuestos_empresariales',
        'agenda_acceso', 'agenda_ver_todas', 'agenda_crear', 'agenda_editar', 'agenda_completar', 'agenda_cancelar',
        'ver_cobranzas', 'registrar_cobro_credito',
        'ver_gastos_corrientes', 'crear_gastos_corrientes', 'editar_gastos_corrientes',
        'registrar_pago_gasto_corriente',
        'gastronomia_acceso', 'gastronomia_pos', 'gastronomia_caja',
    ],
    'Vendedor': [
        'ver_inventario', 'crear_cliente', 'ver_clientes',
        'enviar_caja_venta', 'enviar_caja_reparacion', 'ver_proveedores',
        'ver_reparaciones', 'crear_reparacion',
        'ver_recepcion_usados', 'crear_recepcion_usados',
        'ver_presupuestos_empresariales', 'crear_presupuestos_empresariales',
        'agenda_acceso', 'agenda_crear', 'agenda_editar', 'agenda_completar', 'agenda_cancelar',
        'gastronomia_acceso', 'gastronomia_pos', 'gastronomia_salon',
    ],
    'Tecnico': [
        'ver_clientes', 'crear_cliente',
        'ver_reparaciones', 'crear_reparacion', 'editar_reparacion',
        'cambiar_estado_reparacion',
        'agenda_acceso', 'agenda_crear', 'agenda_editar', 'agenda_completar', 'agenda_cancelar',
    ],
    'Cocina': ['gastronomia_acceso', 'gastronomia_cocina'],
    'Mozo': ['gastronomia_acceso', 'gastronomia_pos', 'gastronomia_salon'],
    'Caja Gastronomia': ['gastronomia_acceso', 'gastronomia_caja'],
    'Delivery Gastronomia': ['gastronomia_acceso', 'gastronomia_delivery', 'gastronomia_delivery_gps'],
    'Auditoria': ['ver_auditoria'],
}
