ESTADO_PEDIDO_BORRADOR = 'borrador'
ESTADO_PEDIDO_PENDIENTE_SENA = 'pendiente_sena'
ESTADO_PEDIDO_EN_PREPARACION = 'en_preparacion'
ESTADO_PEDIDO_PAGO_PARCIAL = 'pago_parcial'
ESTADO_PEDIDO_PAGADO = 'pagado'
ESTADO_PEDIDO_ENTREGADO = 'entregado'
ESTADO_PEDIDO_CANCELADO = 'cancelado'

ESTADOS_PEDIDO = (
    ESTADO_PEDIDO_BORRADOR,
    ESTADO_PEDIDO_PENDIENTE_SENA,
    ESTADO_PEDIDO_EN_PREPARACION,
    ESTADO_PEDIDO_PAGO_PARCIAL,
    ESTADO_PEDIDO_PAGADO,
    ESTADO_PEDIDO_ENTREGADO,
    ESTADO_PEDIDO_CANCELADO,
)

ESTADOS_EDITABLES_PEDIDO = {
    ESTADO_PEDIDO_BORRADOR,
    ESTADO_PEDIDO_PENDIENTE_SENA,
    ESTADO_PEDIDO_EN_PREPARACION,
    ESTADO_PEDIDO_PAGO_PARCIAL,
    ESTADO_PEDIDO_PAGADO,
}

ESTADOS_BLOQUEADOS_PEDIDO = {
    ESTADO_PEDIDO_ENTREGADO,
    ESTADO_PEDIDO_CANCELADO,
}

ESTADOS_GESTIONABLES_SPRINT_1 = (
    ESTADO_PEDIDO_BORRADOR,
    ESTADO_PEDIDO_PENDIENTE_SENA,
    ESTADO_PEDIDO_EN_PREPARACION,
    ESTADO_PEDIDO_CANCELADO,
)

ESTADOS_LABELS = {
    ESTADO_PEDIDO_BORRADOR: 'Borrador',
    ESTADO_PEDIDO_PENDIENTE_SENA: 'Pendiente de sena',
    ESTADO_PEDIDO_EN_PREPARACION: 'En preparacion',
    ESTADO_PEDIDO_PAGO_PARCIAL: 'Pago parcial',
    ESTADO_PEDIDO_PAGADO: 'Pagado',
    ESTADO_PEDIDO_ENTREGADO: 'Entregado',
    ESTADO_PEDIDO_CANCELADO: 'Cancelado',
}


def label_estado_pedido(estado: str) -> str:
    return ESTADOS_LABELS.get((estado or '').strip(), (estado or '').replace('_', ' ').title())
