def _tool(name: str, description: str) -> dict:
    return {
        'type': 'function',
        'function': {
            'name': name,
            'description': description,
            'parameters': {
                'type': 'object',
                'properties': {
                    'periodo': {
                        'type': 'string',
                        'enum': ['hoy', 'ayer', '7d', '30d', 'mes', 'trimestre', 'anio', 'custom'],
                    },
                    'desde': {'type': 'string', 'description': 'Fecha YYYY-MM-DD si periodo=custom'},
                    'hasta': {'type': 'string', 'description': 'Fecha YYYY-MM-DD si periodo=custom'},
                    'periodo_actual': {
                        'type': 'string',
                        'enum': ['hoy', 'ayer', '7d', '30d', 'mes', 'trimestre', 'anio', 'custom'],
                    },
                    'desde_actual': {'type': 'string', 'description': 'Fecha YYYY-MM-DD para el periodo actual si aplica'},
                    'hasta_actual': {'type': 'string', 'description': 'Fecha YYYY-MM-DD para el periodo actual si aplica'},
                    'periodo_anterior': {
                        'type': 'string',
                        'enum': ['hoy', 'ayer', '7d', '30d', 'mes', 'trimestre', 'anio', 'custom'],
                    },
                    'desde_anterior': {'type': 'string', 'description': 'Fecha YYYY-MM-DD para el periodo anterior si aplica'},
                    'hasta_anterior': {'type': 'string', 'description': 'Fecha YYYY-MM-DD para el periodo anterior si aplica'},
                    'top_n': {'type': 'integer', 'minimum': 1, 'maximum': 20},
                    'id_sesion': {'type': 'integer', 'minimum': 1, 'description': 'ID de sesion/cierre de caja si aplica'},
                    'id_cliente': {'type': 'integer', 'minimum': 1, 'description': 'ID de cliente si aplica'},
                    'id_producto': {'type': 'integer', 'minimum': 1, 'description': 'ID de producto si aplica'},
                    'id_venta': {'type': 'integer', 'minimum': 1, 'description': 'ID de venta si aplica'},
                    'busqueda': {'type': 'string', 'description': 'Texto para localizar cliente, producto o venta'},
                    'referencia': {'type': 'string', 'description': 'Alias alternativo de busqueda para documentos o entidades'},
                    'modulo': {'type': 'string', 'description': 'Nombre del modulo a explicar, por ejemplo ventas, fidelizacion, caja o agenda.'},
                    'concepto': {'type': 'string', 'description': 'Concepto de negocio a explicar o calcular, por ejemplo ganancia_neta, ganancia_bruta, margen_bruto, resultado_caja o diferencia_cierre_caja.'},
                    'comparar_con': {'type': 'string', 'description': 'Segundo concepto para comparacion, por ejemplo resultado_caja.'},
                    'objetivo': {'type': 'string', 'description': 'Objetivo comercial para borradores CRM'},
                },
                'additionalProperties': False,
            },
        },
    }


BACKOFFICE_TOOLS = [
    _tool('ventas_resumen_periodo', 'Resumen agregado de ventas, cantidad, ticket promedio y variacion.'),
    _tool('ventas_ganancia_periodo', 'Ganancia bruta estimada, costo estimado, margen y descuentos de ventas.'),
    _tool('ventas_top_productos', 'Productos mas vendidos por ingreso y unidades.'),
    _tool('ventas_rentabilidad_productos', 'Productos mas rentables por ganancia estimada y margen.'),
    _tool('ventas_productos_bajo_margen', 'Productos vendidos con menor margen estimado para revisar precios o costos.'),
    _tool('ventas_descuentos_periodo', 'Resumen de descuentos aplicados en ventas y lineas del periodo.'),
    _tool('ventas_por_categoria', 'Ventas agrupadas por categoria con participacion y variacion.'),
    _tool('ventas_tendencia', 'Serie diaria compacta de ventas del periodo.'),
    _tool('ventas_ranking_mensual', 'Ranking mensual de ventas del periodo con mejor mes y detalle por mes.'),
    _tool('ventas_por_vendedor', 'Ventas agrupadas por vendedor para usuarios autorizados.'),
    _tool('ventas_recomendaciones_crecimiento', 'Diagnostico accionable para vender mas combinando ventas, margen, stock y clientes.'),
    _tool('cobranzas_resumen', 'Resumen de saldo pendiente, cuentas abiertas, vencidas y cobros del periodo.'),
    _tool('cobranzas_clientes_morosos', 'Top clientes con saldo vencido.'),
    _tool('cobranzas_proximos_vencimientos', 'Cuentas por cobrar proximas a vencer.'),
    _tool('inventario_resumen', 'Resumen agregado de stock, productos bajos y valor a costo.'),
    _tool('inventario_productos_baja_rotacion', 'Productos activos con stock, pocas o cero ventas, exceso de stock y recomendacion de oferta o remate.'),
    _tool('inventario_productos_reponer', 'Productos activos que estan en o por debajo del stock minimo.'),
    _tool('inventario_productos_inmovilizados', 'Productos con stock y sin ventas en el periodo.'),
    _tool('gastos_resumen_periodo', 'Resumen de gastos corrientes estimados, pagados, pendientes y vencidos.'),
    _tool('gastos_por_categoria', 'Gastos corrientes agrupados por categoria.'),
    _tool('gastos_vencidos', 'Lista compacta de gastos corrientes vencidos.'),
    _tool('caja_resumen_periodo', 'Resumen agregado de ventas, movimientos y metodos de pago de caja.'),
    _tool('caja_estado_actual', 'Sesiones de caja abiertas y estado actual compacto.'),
    _tool('caja_anulaciones_periodo', 'Anulaciones de ventas auditadas y egresos asociados del periodo.'),
    _tool('caja_cierres_recientes', 'Ultimos cierres de caja con sistema, declarado y diferencia.'),
    _tool('caja_cierre_detalle', 'Detalle compacto de un cierre de caja y sus conceptos principales.'),
    _tool('caja_cierre_diferencia', 'Explicacion de faltante, sobrante o cuadre de un cierre de caja.'),
    _tool('caja_cierre_metodos_pago', 'Desglose por metodos de pago de ventas, creditos, pedidos y compras del cierre.'),
    _tool('caja_cierre_movimientos', 'Movimientos relevantes de caja dentro de un cierre.'),
    _tool('caja_cierre_anulaciones', 'Anulaciones incluidas en un cierre de caja.'),
    _tool('clientes_resumen_inteligencia', 'Resumen de clientes para activar, segmentos y oportunidades comerciales.'),
    _tool('clientes_top_valor', 'Clientes con mayor valor comprado en el periodo.'),
    _tool('clientes_para_contactar', 'Clientes recomendados para contacto comercial con motivo y prioridad.'),
    _tool('crm_sugerir_mensaje', 'Genera un borrador de mensaje CRM sin enviarlo automaticamente.'),
    _tool('modulo_funcionamiento', 'Explica de forma funcional como opera un modulo del sistema sin exponer codigo ni secretos.'),
    _tool('fidelizacion_resumen', 'Resumen del modulo de fidelizacion, su regla actual, beneficios y saldos acumulados.'),
    _tool('cliente_detalle_360', 'Vista 360 de un cliente con ventas, cobranzas, reparaciones e insights accionables.'),
    _tool('producto_detalle_360', 'Vista 360 de un producto con inventario, ventas e insights de rotacion y margen.'),
    _tool('comparar_periodos_negocio', 'Compara ventas, cobranzas e inventario entre dos periodos de negocio.'),
    _tool('hallazgos_operativos_priorizados', 'Detecta hallazgos priorizados de inventario, cobranzas, gastos, clientes y caja.'),
    _tool('metricas_explicacion_negocio', 'Explica conceptos como ganancia bruta, ganancia neta, margen bruto, resultado de caja y diferencia de cierre.'),
    _tool('metricas_comparacion_negocio', 'Compara dos metricas de negocio y explica por que pueden diferir, por ejemplo ganancia neta vs resultado de caja.'),
    _tool('metricas_resumen_operativo', 'Resume ventas, rentabilidad estimada, gastos corrientes y caja del periodo para explicar el resultado operativo.'),
    _tool('detalle_venta_documento', 'Detalle completo de un documento de venta, items, pagos y relaciones.'),
    _tool('empleados_resumen', 'Resumen de empleados activos, salarios base, pagos, extras y descuentos del periodo.'),
    _tool('empleados_ausencias_periodo', 'Ausencias de empleados agrupadas por tipo, estado y empleados destacados.'),
    _tool('empleados_pagos_periodo', 'Pagos de empleados del periodo y pendientes estimados.'),
    _tool('empleados_aguinaldo_resumen', 'Aguinaldo acumulado y proyectado usando el calculador existente.'),
    _tool('reparaciones_resumen', 'Resumen de reparaciones ingresadas, abiertas, listas y costos del periodo.'),
    _tool('reparaciones_atrasadas', 'Reparaciones activas con fecha estimada vencida.'),
    _tool('reparaciones_por_tecnico', 'Carga de reparaciones agrupada por tecnico.'),
    _tool('reparaciones_fallas_frecuentes', 'Fallas reportadas mas frecuentes en reparaciones del periodo.'),
    _tool('tienda_resumen_analytics', 'Resumen de visitas, consultas, conversion y productos vistos de tienda por cliente.'),
    _tool('tienda_productos_mucha_vista_poca_consulta', 'Productos con muchas visitas y baja conversion a consulta.'),
    _tool('tienda_ofertas_rendimiento', 'Rendimiento de promociones activas de tienda por visitas y consultas.'),
    _tool('pedidos_resumen', 'Resumen de pedidos por estado, total, cobrado y saldo pendiente.'),
    _tool('pedidos_pagos_pendientes', 'Pedidos con saldo pendiente ordenados por monto.'),
    _tool('compras_resumen_periodo', 'Resumen de compras, productos mas comprados, costos y estado por periodo.'),
    _tool('proveedores_top', 'Ranking de proveedores por monto comprado, frecuencia, ultima compra y saldo pendiente.'),
    _tool('proveedor_detalle_360', 'Vista integral de un proveedor con compras, saldo, ultima compra y productos asociados.'),
    _tool('devoluciones_resumen', 'Resumen comercial de devoluciones, monto devuelto y acciones de stock.'),
    _tool('productos_mas_devueltos', 'Productos con mas devoluciones por unidades y monto.'),
    _tool('motivos_de_devolucion', 'Motivos mas frecuentes de devoluciones comerciales.'),
    _tool('usados_resumen', 'Resumen de recepciones de equipos usados comprados.'),
    _tool('usados_pendientes_revision', 'Recepciones de usados pendientes de producto o compra asociada.'),
    _tool('usados_margen_estimado', 'Margen estimado de usados usando costo de compra y precio de venta actual.'),
    _tool('usados_por_estado', 'Recepciones de usados agrupadas por estado operativo.'),
    _tool('presupuestos_resumen', 'Resumen de presupuestos empresariales emitidos por periodo.'),
    _tool('presupuestos_pendientes', 'Ultimos presupuestos empresariales pendientes o vigentes para seguimiento.'),
    _tool('presupuestos_conversion', 'Conversion aproximada de presupuestos empresariales usando impresiones como senal.'),
    _tool('presupuesto_detalle', 'Detalle de un presupuesto empresarial por ID o referencia.'),
    _tool('turnos_resumen', 'Resumen de agenda, turnos y actividades por estado y tipo.'),
    _tool('turnos_proximos', 'Proximos turnos o actividades pendientes de agenda.'),
    _tool('turnos_cancelados', 'Turnos o actividades canceladas del periodo.'),
    _tool('atenciones_resumen', 'Resumen de atenciones agendadas en modulos de salud/servicio.'),
    _tool('buscar_entidad_backoffice', 'Busca clientes, productos, ventas, compras, reparaciones, pedidos o proveedores desde una frase.'),
    _tool('dashboard_operativo_hoy', 'Resumen ejecutivo de hoy: ventas, caja, cobranzas, gastos, atrasos, pedidos y stock critico.'),
]
